name: CI Build & Helm Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev|stage|prod)"
        required: true
        default: "dev"
        type: choice
        options: [ "dev", "stage", "prod" ]
      image_tag:
        description: "Optional custom image tag (defaults to 1.0.0)"
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: srividya-testing/nodejs-starter
  DEFAULT_TAG: 1.0.0
  CHART_DIR: charts/nodeapp
  RELEASE_NAME: nodeapp
  DEFAULT_NAMESPACE: app-demo

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_ref: ${{ steps.set_ref.outputs.image_ref }}
      image_tag: ${{ steps.extract_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses
